version: '3.8'

services:
  postgres:
    container_name: nest-project-bd
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_project
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    